Add port config
thomseddon/traefik-forward-auth pull request #230
Opened 2021-01-29 16:05 UTC by hesstobi

I liked to configure the port the server is running on. This mr add this options.

Please let me know if there are any changes required.

2021-01-31 20:58 UTC, thomseddon requested changes
I like this change - thanks!

Please could I ask that you:

- Change the text from "port the server is running on" to "port to listen on"
- Please ensure the text in the readme exactly matches the output of --help

2021-02-01 07:31 UTC, hesstobi commented
Yes of course. The requested changes are implemented.

2021-02-01 20:09 UTC, thomseddon approved these changes

2021-02-01 20:10 UTC, merged

2021-02-01 20:10 UTC, thomseddon commented
Awesome, thanks 👍